## Using  UCI Machine Learning Repository and in  particular Automobile Data Set 

Credit :
http://pbpython.com/categorical-encoding.html
http://www.willmcginnis.com/2015/11/29/beyond-one-hot-an-exploration-of-categorical-variables/

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Define the headers since the data does not have any
headers = ["symboling", "normalized_losses", "make", "fuel_type", "aspiration",
           "num_doors", "body_style", "drive_wheels", "engine_location",
           "wheel_base", "length", "width", "height", "curb_weight",
           "engine_type", "num_cylinders", "engine_size", "fuel_system",
           "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm",
           "city_mpg", "highway_mpg", "price"]

# Read in the CSV file and convert "?" to NaN
df = pd.read_csv("http://mlr.cs.umass.edu/ml/machine-learning-databases/autos/imports-85.data",
                  header=None, names=headers, na_values="?" )
df.head()

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [5]:
df.count()

symboling            205
normalized_losses    164
make                 205
fuel_type            205
aspiration           205
num_doors            203
body_style           205
drive_wheels         205
engine_location      205
wheel_base           205
length               205
width                205
height               205
curb_weight          205
engine_type          205
num_cylinders        205
engine_size          205
fuel_system          205
bore                 201
stroke               201
compression_ratio    205
horsepower           203
peak_rpm             203
city_mpg             205
highway_mpg          205
price                201
dtype: int64

In [4]:
df['normalized_losses'].unique()

array([  nan,  164.,  158.,  192.,  188.,  121.,   98.,   81.,  118.,
        148.,  110.,  145.,  137.,  101.,   78.,  106.,   85.,  107.,
        104.,  113.,  150.,  129.,  115.,   93.,  142.,  161.,  153.,
        125.,  128.,  122.,  103.,  168.,  108.,  194.,  231.,  119.,
        154.,   74.,  186.,   83.,  102.,   89.,   87.,   77.,   91.,
        134.,   65.,  197.,   90.,   94.,  256.,   95.])

## Counting the Nan values

In [6]:
df['normalized_losses'].value_counts(dropna = False)

NaN       41
 161.0    11
 91.0      8
 150.0     7
 104.0     6
 134.0     6
 128.0     6
 94.0      5
 74.0      5
 85.0      5
 103.0     5
 168.0     5
 95.0      5
 102.0     5
 65.0      5
 93.0      4
 148.0     4
 106.0     4
 122.0     4
 118.0     4
 83.0      3
 154.0     3
 125.0     3
 137.0     3
 101.0     3
 115.0     3
 89.0      2
 110.0     2
 145.0     2
 119.0     2
 197.0     2
 164.0     2
 108.0     2
 188.0     2
 129.0     2
 81.0      2
 192.0     2
 158.0     2
 153.0     2
 87.0      2
 194.0     2
 113.0     2
 121.0     1
 98.0      1
 186.0     1
 78.0      1
 107.0     1
 77.0      1
 90.0      1
 256.0     1
 231.0     1
 142.0     1
Name: normalized_losses, dtype: int64

## since iam interested  in  encoding categorial  variables for my further machine learning consumption i need to know the data types ##

### object datatypes are categorical ###

In [7]:
df.dtypes

symboling              int64
normalized_losses    float64
make                  object
fuel_type             object
aspiration            object
num_doors             object
body_style            object
drive_wheels          object
engine_location       object
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
num_cylinders         object
engine_size            int64
fuel_system           object
bore                 float64
stroke               float64
compression_ratio    float64
horsepower           float64
peak_rpm             float64
city_mpg               int64
highway_mpg            int64
price                float64
dtype: object

In [8]:
df_obj = df.select_dtypes(include=['object']).copy()
df_obj.head()

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system
0,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
1,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
2,alfa-romero,gas,std,two,hatchback,rwd,front,ohcv,six,mpfi
3,audi,gas,std,four,sedan,fwd,front,ohc,four,mpfi
4,audi,gas,std,four,sedan,4wd,front,ohc,five,mpfi

In [9]:
df_obj.isnull().any()

make               False
fuel_type          False
aspiration         False
num_doors           True
body_style         False
drive_wheels       False
engine_location    False
engine_type        False
num_cylinders      False
fuel_system        False
dtype: bool

In [10]:
df_obj[df_obj.isnull().any(axis=1)]

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system
27,dodge,gas,turbo,NaN,sedan,fwd,front,ohc,four,mpfi
63,mazda,diesel,std,NaN,sedan,fwd,front,ohc,four,idi

In [11]:
df['num_doors'].value_counts(dropna=False)

four    114
two      89
NaN       2
Name: num_doors, dtype: int64

In [12]:
df_obj = df_obj.fillna({"num_doors": "four"})

In [13]:
df_obj['num_doors'].value_counts(dropna=False)

four    116
two      89
Name: num_doors, dtype: int64

In [56]:
## Option 1 :  Find and replace

In [14]:
df_obj.head()

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system
0,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
1,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
2,alfa-romero,gas,std,two,hatchback,rwd,front,ohcv,six,mpfi
3,audi,gas,std,four,sedan,fwd,front,ohc,four,mpfi
4,audi,gas,std,four,sedan,4wd,front,ohc,five,mpfi

In [15]:
for i  in  {'make','num_cylinders', 'num_doors'}:
    k = df_obj[i].value_counts()
    print('feature :  ', i)
    print(k)
    print()

feature :   make
toyota           32
nissan           18
mazda            17
honda            13
mitsubishi       13
subaru           12
volkswagen       12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
plymouth          7
audi              7
saab              6
porsche           5
isuzu             4
alfa-romero       3
jaguar            3
chevrolet         3
renault           2
mercury           1
Name: make, dtype: int64

feature :   num_doors
four    116
two      89
Name: num_doors, dtype: int64

feature :   num_cylinders
four      159
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: num_cylinders, dtype: int64

In [ ]:
## Below we created the dictionary of items to replace

In [18]:
cleanup_nums = {"num_doors":     {"four": 4, "two": 2},
                "num_cylinders": {"four": 4, "six": 6, "five": 5, "eight": 8,
                                  "two": 2, "twelve": 12, "three":3 }}

In [ ]:
## Now we would replace

In [20]:

df_obj.replace(cleanup_nums , inplace = True)

In [22]:
df_obj.head()

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system
0,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi
1,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi
2,alfa-romero,gas,std,2,hatchback,rwd,front,ohcv,6,mpfi
3,audi,gas,std,4,sedan,fwd,front,ohc,4,mpfi
4,audi,gas,std,4,sedan,4wd,front,ohc,5,mpfi

In [23]:
df_obj.dtypes

make               object
fuel_type          object
aspiration         object
num_doors           int64
body_style         object
drive_wheels       object
engine_location    object
engine_type        object
num_cylinders       int64
fuel_system        object
dtype: object

# So beauty with the replace is that the pandas know it's a numeric field .so you dont need to worry now

## Approach 2 : Label encoding

Another approach to encoding categorical values is to use a technique called label encoding. Label encoding is simply converting each value in a column to a number. 

One trick you can use in pandas is to convert a column to a category, then use those category values for your label encoding:

Label encoding has the advantage that it is straightforward but it has the disadvantage that the numeric values can be “misinterpreted” by the algorithms. For example, the value of 0 is obviously less than the value of 4 but does that really correspond to the data set in real life?

In [27]:
df_obj['body_style'] = df_obj['body_style'].astype('category')

In [28]:
df_obj.dtypes

make                 object
fuel_type            object
aspiration           object
num_doors             int64
body_style         category
drive_wheels         object
engine_location      object
engine_type          object
num_cylinders         int64
fuel_system          object
dtype: object

In [30]:
df_obj["body_style_cat"] = df_obj["body_style"].cat.codes
df_obj

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system,body_style_cat
0,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,0
1,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,0
2,alfa-romero,gas,std,2,hatchback,rwd,front,ohcv,6,mpfi,2
3,audi,gas,std,4,sedan,fwd,front,ohc,4,mpfi,3
4,audi,gas,std,4,sedan,4wd,front,ohc,5,mpfi,3
5,audi,gas,std,2,sedan,fwd,front,ohc,5,mpfi,3
6,audi,gas,std,4,sedan,fwd,front,ohc,5,mpfi,3
7,audi,gas,std,4,wagon,fwd,front,ohc,5,mpfi,4
8,audi,gas,turbo,4,sedan,fwd,front,ohc,5,mpfi,3
9,audi,gas,turbo,2,hatchback,4wd,front,ohc,5,mpfi,2
10,bmw,gas,std,2,sedan,rwd,front,ohc,4,mpfi,3
11,bmw,gas,std,4,sedan,rwd,front,ohc,4,mpfi,3
12,bmw,gas,std,2,sedan,rwd,front,ohc,6,mpfi,3
13,bmw,gas,std,4,sedan,rwd,front,ohc,6,mpfi,3
14,bmw,gas,std,4,sedan,rwd,front,ohc,6,mpfi,3
15,bmw,gas,std,4,sedan,rwd,front,ohc,6,mpfi,3
16,bmw,gas,std,2,sedan,rwd,front,ohc,6,mpfi,3
17,bmw,gas,std,4,sedan,rwd,front,ohc,6,mpfi,3
18,chevrolet,gas,std,2,hatchback,fwd,front,l,3,2bbl,2
19,chevrolet,gas,std,2,hatchback,fwd,front,ohc,4,2bbl,2
20,chevrolet,gas,std,4,sedan,fwd,front,ohc,4,2bbl,3
21,dodge,gas,std,2,hatchback,fwd,front,ohc,4,2bbl,2
22,dodge,gas,std,2,hatchback,fwd,front,ohc,4,2bbl,2
23,dodge,gas,turbo,2,hatchback,fwd,front,ohc,4,mpfi,2
24,dodge,gas,std,4,hatchback,fwd,front,ohc,4,2bbl,2
25,dodge,gas,std,4,sedan,fwd,front,ohc,4,2bbl,3
26,dodge,gas,std,4,sedan,fwd,front,ohc,4,2bbl,3
27,dodge,gas,turbo,4,sedan,fwd,front,ohc,4,mpfi,3
28,dodge,gas,std,4,wagon,fwd,front,ohc,4,2bbl,4
29,dodge,gas,turbo,2,hatchback,fwd,front,ohc,4,mfi,2
...,...,...,...,...,...,...,...,...,...,...,...
175,toyota,gas,std,4,hatchback,fwd,front,ohc,4,mpfi,2
176,toyota,gas,std,4,sedan,fwd,front,ohc,4,mpfi,3
177,toyota,gas,std,4,hatchback,fwd,front,ohc,4,mpfi,2
178,toyota,gas,std,2,hatchback,rwd,front,dohc,6,mpfi,2
179,toyota,gas,std,2,hatchback,rwd,front,dohc,6,mpfi,2
180,toyota,gas,std,4,sedan,rwd,front,dohc,6,mpfi,3
181,toyota,gas,std,4,wagon,rwd,front,dohc,6,mpfi,4
182,volkswagen,diesel,std,2,sedan,fwd,front,ohc,4,idi,3
183,volkswagen,gas,std,2,sedan,fwd,front,ohc,4,mpfi,3
184,volkswagen,diesel,std,4,sedan,fwd,front,ohc,4,idi,3
185,volkswagen,gas,std,4,sedan,fwd,front,ohc,4,mpfi,3
186,volkswagen,gas,std,4,sedan,fwd,front,ohc,4,mpfi,3
187,volkswagen,diesel,turbo,4,sedan,fwd,front,ohc,4,idi,3
188,volkswagen,gas,std,4,sedan,fwd,front,ohc,4,mpfi,3
189,volkswagen,gas,std,2,convertible,fwd,front,ohc,4,mpfi,0
190,volkswagen,gas,std,2,hatchback,fwd,front,ohc,4,mpfi,2
191,volkswagen,gas,std,4,sedan,fwd,front,ohc,5,mpfi,3
192,volkswagen,diesel,turbo,4,sedan,fwd,front,ohc,4,idi,3
193,volkswagen,gas,std,4,wagon,fwd,front,ohc,4,mpfi,4
194,volvo,gas,std,4,sedan,rwd,front,ohc,4,mpfi,3
195,volvo,gas,std,4,wagon,rwd,front,ohc,4,mpfi,4
196,volvo,gas,std,4,sedan,rwd,front,ohc,4,mpfi,3
197,volvo,gas,std,4,wagon,rwd,front,ohc,4,mpfi,4
198,volvo,gas,turbo,4,sedan,rwd,front,ohc,4,mpfi,3
199,volvo,gas,turbo,4,wagon,rwd,front,ohc,4,mpfi,4
200,volvo,gas,std,4,sedan,rwd,front,ohc,4,mpfi,3
201,volvo,gas,turbo,4,sedan,rwd,front,ohc,4,mpfi,3
202,volvo,gas,std,4,sedan,rwd,front,ohcv,6,mpfi,3
203,volvo,diesel,turbo,4,sedan,rwd,front,ohc,6,idi,3
204,volvo,gas,turbo,4,sedan,rwd,front,ohc,4,mpfi,3

In [32]:
df_obj["body_style_cat"].unique()

array([0, 2, 3, 4, 1], dtype=int64)

In [41]:
#Below iam trying to apply something similar to  a where clause as in sql

In [45]:
df_obj[df_obj.body_style_cat ==1 ]

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system,body_style_cat
69,mercedes-benz,diesel,turbo,2,hardtop,rwd,front,ohc,5,idi,1
74,mercedes-benz,gas,std,2,hardtop,rwd,front,ohcv,8,mpfi,1
98,nissan,gas,std,2,hardtop,fwd,front,ohc,4,2bbl,1
126,porsche,gas,std,2,hardtop,rwd,rear,ohcf,6,mpfi,1
127,porsche,gas,std,2,hardtop,rwd,rear,ohcf,6,mpfi,1
167,toyota,gas,std,2,hardtop,rwd,front,ohc,4,mpfi,1
168,toyota,gas,std,2,hardtop,rwd,front,ohc,4,mpfi,1
170,toyota,gas,std,2,hardtop,rwd,front,ohc,4,mpfi,1

In [75]:
df_obj.loc[0:5,:]

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system,body_style_cat
0,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,0
1,alfa-romero,gas,std,2,convertible,rwd,front,dohc,4,mpfi,0
2,alfa-romero,gas,std,2,hatchback,rwd,front,ohcv,6,mpfi,2
3,audi,gas,std,4,sedan,fwd,front,ohc,4,mpfi,3
4,audi,gas,std,4,sedan,4wd,front,ohc,5,mpfi,3
5,audi,gas,std,2,sedan,fwd,front,ohc,5,mpfi,3

In [81]:
df_obj.loc[0:5,'make':'drive_wheels']

          make fuel_type aspiration  num_doors   body_style drive_wheels
0  alfa-romero       gas        std          2  convertible          rwd
1  alfa-romero       gas        std          2  convertible          rwd
2  alfa-romero       gas        std          2    hatchback          rwd
3         audi       gas        std          4        sedan          fwd
4         audi       gas        std          4        sedan          4wd
5         audi       gas        std          2        sedan          fwd

In [83]:
df_obj.loc[0:5, ['drive_wheels','num_doors','aspiration']]

  drive_wheels  num_doors aspiration
0          rwd          2        std
1          rwd          2        std
2          rwd          2        std
3          fwd          4        std
4          4wd          4        std
5          fwd          2        std

In [46]:
df_obj.loc[df_obj.body_style_cat == 1 ,:]

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,engine_type,num_cylinders,fuel_system,body_style_cat
69,mercedes-benz,diesel,turbo,2,hardtop,rwd,front,ohc,5,idi,1
74,mercedes-benz,gas,std,2,hardtop,rwd,front,ohcv,8,mpfi,1
98,nissan,gas,std,2,hardtop,fwd,front,ohc,4,2bbl,1
126,porsche,gas,std,2,hardtop,rwd,rear,ohcf,6,mpfi,1
127,porsche,gas,std,2,hardtop,rwd,rear,ohcf,6,mpfi,1
167,toyota,gas,std,2,hardtop,rwd,front,ohc,4,mpfi,1
168,toyota,gas,std,2,hardtop,rwd,front,ohc,4,mpfi,1
170,toyota,gas,std,2,hardtop,rwd,front,ohc,4,mpfi,1

In [55]:
df_obj.loc[df_obj.body_style_cat == 1 , 'make' :'engine_location']

,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location
69,mercedes-benz,diesel,turbo,2,hardtop,rwd,front
74,mercedes-benz,gas,std,2,hardtop,rwd,front
98,nissan,gas,std,2,hardtop,fwd,front
126,porsche,gas,std,2,hardtop,rwd,rear
127,porsche,gas,std,2,hardtop,rwd,rear
167,toyota,gas,std,2,hardtop,rwd,front
168,toyota,gas,std,2,hardtop,rwd,front
170,toyota,gas,std,2,hardtop,rwd,front

In [56]:
df_obj.loc[df_obj.body_style_cat == 1 , ['make' ,'engine_location']]

              make engine_location
69   mercedes-benz           front
74   mercedes-benz           front
98          nissan           front
126        porsche            rear
127        porsche            rear
167         toyota           front
168         toyota           front
170         toyota           front

In [60]:
df_obj.columns

Index(['make', 'fuel_type', 'aspiration', 'num_doors', 'body_style',
       'drive_wheels', 'engine_location', 'engine_type', 'num_cylinders',
       'fuel_system', 'body_style_cat'],
      dtype='object')

In [73]:
# iloc outer range is exclusive whereas loc range is inclusive

In [58]:
df_obj.iloc[: , 0:5]

            make fuel_type aspiration  num_doors   body_style
0    alfa-romero       gas        std          2  convertible
1    alfa-romero       gas        std          2  convertible
2    alfa-romero       gas        std          2    hatchback
3           audi       gas        std          4        sedan
4           audi       gas        std          4        sedan
5           audi       gas        std          2        sedan
6           audi       gas        std          4        sedan
7           audi       gas        std          4        wagon
8           audi       gas      turbo          4        sedan
9           audi       gas      turbo          2    hatchback
10           bmw       gas        std          2        sedan
11           bmw       gas        std          4        sedan
12           bmw       gas        std          2        sedan
13           bmw       gas        std          4        sedan
14           bmw       gas        std          4        sedan
15           bmw       gas        std          4        sedan
16           bmw       gas        std          2        sedan
17           bmw       gas        std          4        sedan
18     chevrolet       gas        std          2    hatchback
19     chevrolet       gas        std          2    hatchback
20     chevrolet       gas        std          4        sedan
21         dodge       gas        std          2    hatchback
22         dodge       gas        std          2    hatchback
23         dodge       gas      turbo          2    hatchback
24         dodge       gas        std          4    hatchback
25         dodge       gas        std          4        sedan
26         dodge       gas        std          4        sedan
27         dodge       gas      turbo          4        sedan
28         dodge       gas        std          4        wagon
29         dodge       gas      turbo          2    hatchback
..           ...       ...        ...        ...          ...
175       toyota       gas        std          4    hatchback
176       toyota       gas        std          4        sedan
177       toyota       gas        std          4    hatchback
178       toyota       gas        std          2    hatchback
179       toyota       gas        std          2    hatchback
180       toyota       gas        std          4        sedan
181       toyota       gas        std          4        wagon
182   volkswagen    diesel        std          2        sedan
183   volkswagen       gas        std          2        sedan
184   volkswagen    diesel        std          4        sedan
185   volkswagen       gas        std          4        sedan
186   volkswagen       gas        std          4        sedan
187   volkswagen    diesel      turbo          4        sedan
188   volkswagen       gas        std          4        sedan
189   volkswagen       gas        std          2  convertible
190   volkswagen       gas        std          2    hatchback
191   volkswagen       gas        std          4        sedan
192   volkswagen    diesel      turbo          4        sedan
193   volkswagen       gas        std          4        wagon
194        volvo       gas        std          4        sedan
195        volvo       gas        std          4        wagon
196        volvo       gas        std          4        sedan
197        volvo       gas        std          4        wagon
198        volvo       gas      turbo          4        sedan
199        volvo       gas      turbo          4        wagon
200        volvo       gas        std          4        sedan
201        volvo       gas      turbo          4        sedan
202        volvo       gas        std          4        sedan
203        volvo    diesel      turbo          4        sedan
204        volvo       gas      turbo          4        sedan

[205 rows x 5 columns]

In [69]:
##Below iam using a AND condition to select some data

In [72]:
df_obj[(df_obj.fuel_type == 'gas') & (df_obj.body_style_cat == 4)].count()

make               22
fuel_type          22
aspiration         22
num_doors          22
body_style         22
drive_wheels       22
engine_location    22
engine_type        22
num_cylinders      22
fuel_system        22
body_style_cat     22
dtype: int64

In [71]:
df_obj[(df_obj.fuel_type == 'gas') | (df_obj.body_style_cat == 4)].count()

make               188
fuel_type          188
aspiration         188
num_doors          188
body_style         188
drive_wheels       188
engine_location    188
engine_type        188
num_cylinders      188
fuel_system        188
body_style_cat     188
dtype: int64

# Approach #3 - One Hot Encoding

A common alternative approach is called one hot encoding (but also goes by several different names shown below). Despite the different names, 

the basic strategy is to convert each category value into a new column and assigns a 1 or 0 (True/False) value to the column. This has the benefit of not weighting a value improperly but does have the downside of adding more columns to the data set.

Pandas supports this feature using get_dummies. This function is named this way because it creates dummy/indicator variables (aka 1 or 0).

In [84]:
df_obj.drive_wheels.unique()

array(['rwd', 'fwd', '4wd'], dtype=object)

In [85]:
df_obj['drive_wheels'].unique()

array(['rwd', 'fwd', '4wd'], dtype=object)

In [89]:
pd.get_dummies(df_obj,columns= ['drive_wheels','body_style'], prefix= ['drive','body'])

,make,fuel_type,aspiration,num_doors,engine_location,engine_type,num_cylinders,fuel_system,body_style_cat,drive_4wd,drive_fwd,drive_rwd,body_convertible,body_hardtop,body_hatchback,body_sedan,body_wagon
0,alfa-romero,gas,std,2,front,dohc,4,mpfi,0,0,0,1,1,0,0,0,0
1,alfa-romero,gas,std,2,front,dohc,4,mpfi,0,0,0,1,1,0,0,0,0
2,alfa-romero,gas,std,2,front,ohcv,6,mpfi,2,0,0,1,0,0,1,0,0
3,audi,gas,std,4,front,ohc,4,mpfi,3,0,1,0,0,0,0,1,0
4,audi,gas,std,4,front,ohc,5,mpfi,3,1,0,0,0,0,0,1,0
5,audi,gas,std,2,front,ohc,5,mpfi,3,0,1,0,0,0,0,1,0
6,audi,gas,std,4,front,ohc,5,mpfi,3,0,1,0,0,0,0,1,0
7,audi,gas,std,4,front,ohc,5,mpfi,4,0,1,0,0,0,0,0,1
8,audi,gas,turbo,4,front,ohc,5,mpfi,3,0,1,0,0,0,0,1,0
9,audi,gas,turbo,2,front,ohc,5,mpfi,2,1,0,0,0,0,1,0,0
10,bmw,gas,std,2,front,ohc,4,mpfi,3,0,0,1,0,0,0,1,0
11,bmw,gas,std,4,front,ohc,4,mpfi,3,0,0,1,0,0,0,1,0
12,bmw,gas,std,2,front,ohc,6,mpfi,3,0,0,1,0,0,0,1,0
13,bmw,gas,std,4,front,ohc,6,mpfi,3,0,0,1,0,0,0,1,0
14,bmw,gas,std,4,front,ohc,6,mpfi,3,0,0,1,0,0,0,1,0
15,bmw,gas,std,4,front,ohc,6,mpfi,3,0,0,1,0,0,0,1,0
16,bmw,gas,std,2,front,ohc,6,mpfi,3,0,0,1,0,0,0,1,0
17,bmw,gas,std,4,front,ohc,6,mpfi,3,0,0,1,0,0,0,1,0
18,chevrolet,gas,std,2,front,l,3,2bbl,2,0,1,0,0,0,1,0,0
19,chevrolet,gas,std,2,front,ohc,4,2bbl,2,0,1,0,0,0,1,0,0
20,chevrolet,gas,std,4,front,ohc,4,2bbl,3,0,1,0,0,0,0,1,0
21,dodge,gas,std,2,front,ohc,4,2bbl,2,0,1,0,0,0,1,0,0
22,dodge,gas,std,2,front,ohc,4,2bbl,2,0,1,0,0,0,1,0,0
23,dodge,gas,turbo,2,front,ohc,4,mpfi,2,0,1,0,0,0,1,0,0
24,dodge,gas,std,4,front,ohc,4,2bbl,2,0,1,0,0,0,1,0,0
25,dodge,gas,std,4,front,ohc,4,2bbl,3,0,1,0,0,0,0,1,0
26,dodge,gas,std,4,front,ohc,4,2bbl,3,0,1,0,0,0,0,1,0
27,dodge,gas,turbo,4,front,ohc,4,mpfi,3,0,1,0,0,0,0,1,0
28,dodge,gas,std,4,front,ohc,4,2bbl,4,0,1,0,0,0,0,0,1
29,dodge,gas,turbo,2,front,ohc,4,mfi,2,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,toyota,gas,std,4,front,ohc,4,mpfi,2,0,1,0,0,0,1,0,0
176,toyota,gas,std,4,front,ohc,4,mpfi,3,0,1,0,0,0,0,1,0
177,toyota,gas,std,4,front,ohc,4,mpfi,2,0,1,0,0,0,1,0,0
178,toyota,gas,std,2,front,dohc,6,mpfi,2,0,0,1,0,0,1,0,0
179,toyota,gas,std,2,front,dohc,6,mpfi,2,0,0,1,0,0,1,0,0
180,toyota,gas,std,4,front,dohc,6,mpfi,3,0,0,1,0,0,0,1,0
181,toyota,gas,std,4,front,dohc,6,mpfi,4,0,0,1,0,0,0,0,1
182,volkswagen,diesel,std,2,front,ohc,4,idi,3,0,1,0,0,0,0,1,0
183,volkswagen,gas,std,2,front,ohc,4,mpfi,3,0,1,0,0,0,0,1,0
184,volkswagen,diesel,std,4,front,ohc,4,idi,3,0,1,0,0,0,0,1,0
185,volkswagen,gas,std,4,front,ohc,4,mpfi,3,0,1,0,0,0,0,1,0
186,volkswagen,gas,std,4,front,ohc,4,mpfi,3,0,1,0,0,0,0,1,0
187,volkswagen,diesel,turbo,4,front,ohc,4,idi,3,0,1,0,0,0,0,1,0
188,volkswagen,gas,std,4,front,ohc,4,mpfi,3,0,1,0,0,0,0,1,0
189,volkswagen,gas,std,2,front,ohc,4,mpfi,0,0,1,0,1,0,0,0,0
190,volkswagen,gas,std,2,front,ohc,4,mpfi,2,0,1,0,0,0,1,0,0
191,volkswagen,gas,std,4,front,ohc,5,mpfi,3,0,1,0,0,0,0,1,0
192,volkswagen,diesel,turbo,4,front,ohc,4,idi,3,0,1,0,0,0,0,1,0
193,volkswagen,gas,std,4,front,ohc,4,mpfi,4,0,1,0,0,0,0,0,1
194,volvo,gas,std,4,front,ohc,4,mpfi,3,0,0,1,0,0,0,1,0
195,volvo,gas,std,4,front,ohc,4,mpfi,4,0,0,1,0,0,0,0,1
196,volvo,gas,std,4,front,ohc,4,mpfi,3,0,0,1,0,0,0,1,0
197,volvo,gas,std,4,front,ohc,4,mpfi,4,0,0,1,0,0,0,0,1
198,volvo,gas,turbo,4,front,ohc,4,mpfi,3,0,0,1,0,0,0,1,0
199,volvo,gas,turbo,4,front,ohc,4,mpfi,4,0,0,1,0,0,0,0,1
200,volvo,gas,std,4,front,ohc,4,mpfi,3,0,0,1,0,0,0,1,0
201,volvo,gas,turbo,4,front,ohc,4,mpfi,3,0,0,1,0,0,0,1,0
202,volvo,gas,std,4,front,ohcv,6,mpfi,3,0,0,1,0,0,0,1,0
203,volvo,diesel,turbo,4,front,ohc,6,idi,3,0,0,1,0,0,0,1,0
204,volvo,gas,turbo,4,front,ohc,4,mpfi,3,0,0,1,0,0,0,1,0

In [ ]:
Please note that the get_dummies convert all the object type columns (categorial columns) .So be careful and use select_dtypes

In [91]:
pd.get_dummies(df)

,symboling,normalized_losses,wheel_base,length,width,height,curb_weight,engine_size,bore,stroke,...,num_cylinders_twelve,num_cylinders_two,fuel_system_1bbl,fuel_system_2bbl,fuel_system_4bbl,fuel_system_idi,fuel_system_mfi,fuel_system_mpfi,fuel_system_spdi,fuel_system_spfi
0,3,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,...,0,0,0,0,0,0,0,1,0,0
1,3,NaN,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,...,0,0,0,0,0,0,0,1,0,0
2,1,NaN,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,...,0,0,0,0,0,0,0,1,0,0
3,2,164.0,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
4,2,164.0,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
5,2,NaN,99.8,177.3,66.3,53.1,2507,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
6,1,158.0,105.8,192.7,71.4,55.7,2844,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
7,1,NaN,105.8,192.7,71.4,55.7,2954,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
8,1,158.0,105.8,192.7,71.4,55.9,3086,131,3.13,3.40,...,0,0,0,0,0,0,0,1,0,0
9,0,NaN,99.5,178.2,67.9,52.0,3053,131,3.13,3.40,...,0,0,0,0,0,0,0,1,0,0
10,2,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.80,...,0,0,0,0,0,0,0,1,0,0
11,0,192.0,101.2,176.8,64.8,54.3,2395,108,3.50,2.80,...,0,0,0,0,0,0,0,1,0,0
12,0,188.0,101.2,176.8,64.8,54.3,2710,164,3.31,3.19,...,0,0,0,0,0,0,0,1,0,0
13,0,188.0,101.2,176.8,64.8,54.3,2765,164,3.31,3.19,...,0,0,0,0,0,0,0,1,0,0
14,1,NaN,103.5,189.0,66.9,55.7,3055,164,3.31,3.19,...,0,0,0,0,0,0,0,1,0,0
15,0,NaN,103.5,189.0,66.9,55.7,3230,209,3.62,3.39,...,0,0,0,0,0,0,0,1,0,0
16,0,NaN,103.5,193.8,67.9,53.7,3380,209,3.62,3.39,...,0,0,0,0,0,0,0,1,0,0
17,0,NaN,110.0,197.0,70.9,56.3,3505,209,3.62,3.39,...,0,0,0,0,0,0,0,1,0,0
18,2,121.0,88.4,141.1,60.3,53.2,1488,61,2.91,3.03,...,0,0,0,1,0,0,0,0,0,0
19,1,98.0,94.5,155.9,63.6,52.0,1874,90,3.03,3.11,...,0,0,0,1,0,0,0,0,0,0
20,0,81.0,94.5,158.8,63.6,52.0,1909,90,3.03,3.11,...,0,0,0,1,0,0,0,0,0,0
21,1,118.0,93.7,157.3,63.8,50.8,1876,90,2.97,3.23,...,0,0,0,1,0,0,0,0,0,0
22,1,118.0,93.7,157.3,63.8,50.8,1876,90,2.97,3.23,...,0,0,0,1,0,0,0,0,0,0
23,1,118.0,93.7,157.3,63.8,50.8,2128,98,3.03,3.39,...,0,0,0,0,0,0,0,1,0,0
24,1,148.0,93.7,157.3,63.8,50.6,1967,90,2.97,3.23,...,0,0,0,1,0,0,0,0,0,0
25,1,148.0,93.7,157.3,63.8,50.6,1989,90,2.97,3.23,...,0,0,0,1,0,0,0,0,0,0
26,1,148.0,93.7,157.3,63.8,50.6,1989,90,2.97,3.23,...,0,0,0,1,0,0,0,0,0,0
27,1,148.0,93.7,157.3,63.8,50.6,2191,98,3.03,3.39,...,0,0,0,0,0,0,0,1,0,0
28,-1,110.0,103.3,174.6,64.6,59.8,2535,122,3.34,3.46,...,0,0,0,1,0,0,0,0,0,0
29,3,145.0,95.9,173.2,66.3,50.2,2811,156,3.60,3.90,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,-1,65.0,102.4,175.6,66.5,53.9,2414,122,3.31,3.54,...,0,0,0,0,0,0,0,1,0,0
176,-1,65.0,102.4,175.6,66.5,54.9,2414,122,3.31,3.54,...,0,0,0,0,0,0,0,1,0,0
177,-1,65.0,102.4,175.6,66.5,53.9,2458,122,3.31,3.54,...,0,0,0,0,0,0,0,1,0,0
178,3,197.0,102.9,183.5,67.7,52.0,2976,171,3.27,3.35,...,0,0,0,0,0,0,0,1,0,0
179,3,197.0,102.9,183.5,67.7,52.0,3016,171,3.27,3.35,...,0,0,0,0,0,0,0,1,0,0
180,-1,90.0,104.5,187.8,66.5,54.1,3131,171,3.27,3.35,...,0,0,0,0,0,0,0,1,0,0
181,-1,NaN,104.5,187.8,66.5,54.1,3151,161,3.27,3.35,...,0,0,0,0,0,0,0,1,0,0
182,2,122.0,97.3,171.7,65.5,55.7,2261,97,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
183,2,122.0,97.3,171.7,65.5,55.7,2209,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
184,2,94.0,97.3,171.7,65.5,55.7,2264,97,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
185,2,94.0,97.3,171.7,65.5,55.7,2212,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
186,2,94.0,97.3,171.7,65.5,55.7,2275,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
187,2,94.0,97.3,171.7,65.5,55.7,2319,97,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
188,2,94.0,97.3,171.7,65.5,55.7,2300,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
189,3,NaN,94.5,159.3,64.2,55.6,2254,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
190,3,256.0,94.5,165.7,64.0,51.4,2221,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
191,0,NaN,100.4,180.2,66.9,55.1,2661,136,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
192,0,NaN,100.4,180.2,66.9,55.1,2579,97,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
193,0,NaN,100.4,183.1,66.9,55.1,2563,109,3.19,3.40,...,0,0,0,0,0,0,0,1,0,0
194,-2,103.0,104.3,188.8,67.2,56.2,2912,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
195,-1,74.0,104.3,188.8,67.2,57.5,3034,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
196,-2,103.0,104.3,188.8,67.2,56.2,2935,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
197,-1,74.0,104.3,188.8,67.2,57.5,3042,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
198,-2,103.0,104.3,188.8,67.2,56.2,3045,130,3.62,3.15,...,0,0,0,0,0,0,0,1,0,0
199,-1,74.0,104.3,188.8,67.2,57.5,3157,130,3.62,3.15,...,0,0,0,0,0,0,0,1,0,0
200,-1,95.0,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
201,-1,95.0,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0
202,-1,95.0,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,...,0,0,0,0,0,0,0,1,0,0
203,-1,95.0,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,...,0,0,0,0,0,1,0,0,0,0
204,-1,95.0,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,...,0,0,0,0,0,0,0,1,0,0

# Approach #4 - Custom Binary Encoding

In [92]:
# Here we would code boolean 1 or 0 only  . If some ccriteria matches then 1 else 0

We would use the column  engine_type to showcase the example . whereever it comtains "ohc" then 1 else 0

In [93]:
df_obj["engine_type"].value_counts()

ohc      148
ohcf      15
ohcv      13
l         12
dohc      12
rotor      4
dohcv      1
Name: engine_type, dtype: int64

In [103]:
df_obj['OHC_Code'] = np.where(df_obj.engine_type.str.contains('ohc'),1,0)
df_obj.OHC_Code.head()

0    1
1    1
2    1
3    1
4    1
Name: OHC_Code, dtype: int32

# Scikit learn method to encode

 if we want to do a label encoding on the make of the car, we would import a LabelEncoder object and fit_transform on the data

In [105]:
from sklearn.preprocessing import LabelEncoder

lb_make = LabelEncoder()
df_obj["make_code"] = lb_make.fit_transform(df_obj["make"])
df_obj[["make", "make_code"]].head(11)

           make  make_code
0   alfa-romero          0
1   alfa-romero          0
2   alfa-romero          0
3          audi          1
4          audi          1
5          audi          1
6          audi          1
7          audi          1
8          audi          1
9          audi          1
10          bmw          2

In [106]:
## Scikit-learn also supports binary encoding by using the LabelBinarizer.

In [113]:
from sklearn.preprocessing import LabelBinarizer
lb_fuel_system = LabelBinarizer()
lb_results = lb_fuel_system.fit_transform(df_obj['fuel_system'])

pd.DataFrame(lb_results,columns=lb_fuel_system.classes_)

     1bbl  2bbl  4bbl  idi  mfi  mpfi  spdi  spfi
0       0     0     0    0    0     1     0     0
1       0     0     0    0    0     1     0     0
2       0     0     0    0    0     1     0     0
3       0     0     0    0    0     1     0     0
4       0     0     0    0    0     1     0     0
5       0     0     0    0    0     1     0     0
6       0     0     0    0    0     1     0     0
7       0     0     0    0    0     1     0     0
8       0     0     0    0    0     1     0     0
9       0     0     0    0    0     1     0     0
10      0     0     0    0    0     1     0     0
11      0     0     0    0    0     1     0     0
12      0     0     0    0    0     1     0     0
13      0     0     0    0    0     1     0     0
14      0     0     0    0    0     1     0     0
15      0     0     0    0    0     1     0     0
16      0     0     0    0    0     1     0     0
17      0     0     0    0    0     1     0     0
18      0     1     0    0    0     0     0     0
19      0     1     0    0    0     0     0     0
20      0     1     0    0    0     0     0     0
21      0     1     0    0    0     0     0     0
22      0     1     0    0    0     0     0     0
23      0     0     0    0    0     1     0     0
24      0     1     0    0    0     0     0     0
25      0     1     0    0    0     0     0     0
26      0     1     0    0    0     0     0     0
27      0     0     0    0    0     1     0     0
28      0     1     0    0    0     0     0     0
29      0     0     0    0    1     0     0     0
..    ...   ...   ...  ...  ...   ...   ...   ...
175     0     0     0    0    0     1     0     0
176     0     0     0    0    0     1     0     0
177     0     0     0    0    0     1     0     0
178     0     0     0    0    0     1     0     0
179     0     0     0    0    0     1     0     0
180     0     0     0    0    0     1     0     0
181     0     0     0    0    0     1     0     0
182     0     0     0    1    0     0     0     0
183     0     0     0    0    0     1     0     0
184     0     0     0    1    0     0     0     0
185     0     0     0    0    0     1     0     0
186     0     0     0    0    0     1     0     0
187     0     0     0    1    0     0     0     0
188     0     0     0    0    0     1     0     0
189     0     0     0    0    0     1     0     0
190     0     0     0    0    0     1     0     0
191     0     0     0    0    0     1     0     0
192     0     0     0    1    0     0     0     0
193     0     0     0    0    0     1     0     0
194     0     0     0    0    0     1     0     0
195     0     0     0    0    0     1     0     0
196     0     0     0    0    0     1     0     0
197     0     0     0    0    0     1     0     0
198     0     0     0    0    0     1     0     0
199     0     0     0    0    0     1     0     0
200     0     0     0    0    0     1     0     0
201     0     0     0    0    0     1     0     0
202     0     0     0    0    0     1     0     0
203     0     0     0    1    0     0     0     0
204     0     0     0    0    0     1     0     0

[205 rows x 8 columns]